/**
 * Generate `src/version.ts` from package.json.
 *
 * The version was previously hardcoded in three places — the commander
 * `--version` string and the MCP `serverInfo.version` in both the initialize
 * response and the server constructor. All three silently kept saying `0.1.0`
 * after the package moved to 1.0.0, which meant `doctor` and every MCP host
 * reported a version that did not exist.
 *
 * It cannot simply `import '../package.json'`: tsconfig sets `rootDir: src`, and
 * under `bun build --compile` there is no package.json on disk at runtime at all
 * (see src/install/bundlePaths.ts for the same constraint).
 *
 * NOT to be confused with `src/bridge/wireProtocol.ts`'s `PROTOCOL_VERSION`,
 * which is the frame-format version and is deliberately independent of the
 * release version — it is pinned byte-for-byte against the extension's copy and
 * asserted by smoke-test ASSERTION 6.
 *
 * The generated file IS committed, matching the convention used for the vendored
 * instructions. `build` regenerates it, and `--check` fails on drift.
 *
 * Usage:
 *   node scripts/gen-version.mjs
 *   node scripts/gen-version.mjs --check
 *
 * stderr-only, matching scripts/bundle-extension.mjs.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORTAL_MCP_ROOT = path.resolve(__dirname, '..');
const TARGET = path.join(PORTAL_MCP_ROOT, 'src', 'version.ts');

const checkOnly = process.argv.includes('--check');

const { version } = JSON.parse(fs.readFileSync(path.join(PORTAL_MCP_ROOT, 'package.json'), 'utf8'));
if (typeof version !== 'string') {
  console.error('portal-mcp: gen-version — package.json has no version field');
  process.exit(1);
}

const contents = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Regenerate with \`yarn gen-version\`; \`yarn build\` does it for you.
//
// This is the RELEASE version. For the bridge frame-format version see
// PROTOCOL_VERSION in src/bridge/wireProtocol.ts — they are independent.
export const VERSION = '${version}';
`;

const existing = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, 'utf8') : null;
const stale = [];

if (existing !== contents) {
  if (checkOnly) {
    stale.push('src/version.ts');
  } else {
    fs.writeFileSync(TARGET, contents);
    console.error(`portal-mcp: gen-version — wrote src/version.ts (${version})`);
  }
}

/**
 * The Claude Code plugin manifests carry the version twice: their own `version`
 * field, and the npx spec pinned in the plugin's mcpServers args. A stale pin
 * there is the worst kind of drift — the plugin installs cleanly and silently
 * runs an old published version — so they are synced from package.json too.
 */
const PLUGIN_DIR = path.join(PORTAL_MCP_ROOT, '.claude-plugin');
for (const file of ['plugin.json', 'marketplace.json']) {
  const target = path.join(PLUGIN_DIR, file);
  if (!fs.existsSync(target)) continue;

  const before = fs.readFileSync(target, 'utf8');
  const manifest = JSON.parse(before);
  manifest.version = version;

  for (const server of Object.values(manifest.mcpServers ?? {})) {
    if (!Array.isArray(server.args)) continue;
    server.args = server.args.map((arg) =>
      typeof arg === 'string' && arg.startsWith('@darwinium/portal-mcp@')
        ? `@darwinium/portal-mcp@${version}`
        : arg,
    );
  }

  const after = JSON.stringify(manifest, null, 2) + '\n';
  if (after === before) continue;

  if (checkOnly) {
    stale.push(`.claude-plugin/${file}`);
  } else {
    fs.writeFileSync(target, after);
    console.error(`portal-mcp: gen-version — wrote .claude-plugin/${file} (${version})`);
  }
}

if (checkOnly && stale.length > 0) {
  console.error(
    `portal-mcp: gen-version — stale against package.json (${version}): ${stale.join(', ')}. ` +
      'Run `node scripts/gen-version.mjs` and commit the result.',
  );
  process.exit(1);
}

console.error(`portal-mcp: gen-version — ✓ version ${version} is consistent`);
