// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Regenerate with `yarn gen-version`; `yarn build` does it for you.
//
// This is the RELEASE version. For the bridge frame-format version see
// PROTOCOL_VERSION in src/bridge/wireProtocol.ts — they are independent.
export const VERSION = '0.0.2';
